Added **kwargs to catch unused params passed to objectstorage tests
Datasets that contain extra or unexpected parameters to be passed
to the data driven tests result in TypeErrores because the test
recieves unexpected keyword arguments. Adding '**kwargs' to these
tests catches potential 'extra' parameters.

Change-Id: I1cda51ff35a8e267f7eea67829447ae834b029b6